@hostname = subservice.fennellabs.com
@port = 443

###
# @name Health Check
GET /healthcheck
Host: {{hostname}}:{{port}}

###
# @name Create Account
GET /create_account
Host: {{hostname}}:{{port}}

###
# @name Download Account as JSON
POST /download_account_as_json
Host: {{hostname}}:{{port}}
Content-Type: application/json

{
    "mnemonic": "captain calm afraid vehicle fetch stage custom federal assist arrange pumpkin cheese grocery square discover firm kind endorse door tonight name lonely alter wrestle"
}

###
# @name Get Address
POST /get_address
Host: {{hostname}}:{{port}}
Content-Type: application/json

{
    "mnemonic": "captain calm afraid vehicle fetch stage custom federal assist arrange pumpkin cheese grocery square discover firm kind endorse door tonight name lonely alter wrestle"
}

###
# @name Get Account Balance
POST /get_account_balance
Host: {{hostname}}:{{port}}
Content-Type: application/json

{
    "mnemonic": "captain calm afraid vehicle fetch stage custom federal assist arrange pumpkin cheese grocery square discover firm kind endorse door tonight name lonely alter wrestle"
}

###
# @name Get Fee For Transfer Token
POST /get_fee_for_transfer_token
Host: {{hostname}}:{{port}}
Content-Type: application/json

{
    "mnemonic": "captain calm afraid vehicle fetch stage custom federal assist arrange pumpkin cheese grocery square discover firm kind endorse door tonight name lonely alter wrestle",
    "to": "5CwBjJ48HW7c36dT7pAf9TkGQjj88jxw624xHaL6wtXJTWCt",
    "amount": 100000
}

###
# @name Get Fee For Transfer Token
POST /transfer_token
Host: {{hostname}}:{{port}}
Content-Type: application/json

{
    "mnemonic": "captain calm afraid vehicle fetch stage custom federal assist arrange pumpkin cheese grocery square discover firm kind endorse door tonight name lonely alter wrestle",
    "to": "5CwBjJ48HW7c36dT7pAf9TkGQjj88jxw624xHaL6wtXJTWCt",
    "amount": 100000
}

###
# @name Get Fee for New Signal
POST /get_fee_for_new_signal
Host: {{hostname}}:{{port}}
Content-Type: application/json

{
    "mnemonic": "captain calm afraid vehicle fetch stage custom federal assist arrange pumpkin cheese grocery square discover firm kind endorse door tonight name lonely alter wrestle",
    "content": "Testing Message"
}

###
# @name Send New Signal
POST /send_new_signal
Host: {{hostname}}:{{port}}
Content-Type: application/json

{
    "mnemonic": "captain calm afraid vehicle fetch stage custom federal assist arrange pumpkin cheese grocery square discover firm kind endorse door tonight name lonely alter wrestle",
    "content": "Testing Message"
}

###
# @name Get Signal History
POST /get_signal_history
Host: {{hostname}}:{{port}}

###
# @name Get Fee For Issue Trust
POST: /get_fee_for_issue_trust
Host: {{hostname}}:{{port}}

{
    "mnemonic": "captain calm afraid vehicle fetch stage custom federal assist arrange pumpkin cheese grocery square discover firm kind endorse door tonight name lonely alter wrestle",
    "address": "5CwBjJ48HW7c36dT7pAf9TkGQjj88jxw624xHaL6wtXJTWCt"
}

###
# @name Issue Trust
POST: /issue_trust
Host: {{hostname}}:{{port}}

{
    "mnemonic": "captain calm afraid vehicle fetch stage custom federal assist arrange pumpkin cheese grocery square discover firm kind endorse door tonight name lonely alter wrestle",
    "address": "5CwBjJ48HW7c36dT7pAf9TkGQjj88jxw624xHaL6wtXJTWCt"
}

###
# @name Get Fee For Remove Trust
POST: /get_fee_for_remove_trust
Host: {{hostname}}:{{port}}

{
    "mnemonic": "captain calm afraid vehicle fetch stage custom federal assist arrange pumpkin cheese grocery square discover firm kind endorse door tonight name lonely alter wrestle",
    "address": "5CwBjJ48HW7c36dT7pAf9TkGQjj88jxw624xHaL6wtXJTWCt"
}

###
# @name Remove Trust
POST: /remove_trust
Host: {{hostname}}:{{port}}

{
    "mnemonic": "captain calm afraid vehicle fetch stage custom federal assist arrange pumpkin cheese grocery square discover firm kind endorse door tonight name lonely alter wrestle",
    "address": "5CwBjJ48HW7c36dT7pAf9TkGQjj88jxw624xHaL6wtXJTWCt"
}

###
# @name Get Fee for Request Trust
POST: /get_fee_for_request_trust
Host: {{hostname}}:{{port}}

{
    "mnemonic": "captain calm afraid vehicle fetch stage custom federal assist arrange pumpkin cheese grocery square discover firm kind endorse door tonight name lonely alter wrestle",
    "address": "5CwBjJ48HW7c36dT7pAf9TkGQjj88jxw624xHaL6wtXJTWCt"
}

###
# @name Request Trust
POST: /request_trust
Host: {{hostname}}:{{port}}

{
    "mnemonic": "captain calm afraid vehicle fetch stage custom federal assist arrange pumpkin cheese grocery square discover firm kind endorse door tonight name lonely alter wrestle",
    "address": "5CwBjJ48HW7c36dT7pAf9TkGQjj88jxw624xHaL6wtXJTWCt"
}

###
# @name Get Fee for Cancel Trust Request
POST: /get_fee_for_cancel_trust_request
Host: {{hostname}}:{{port}}

{
    "mnemonic": "captain calm afraid vehicle fetch stage custom federal assist arrange pumpkin cheese grocery square discover firm kind endorse door tonight name lonely alter wrestle",
    "address": "5CwBjJ48HW7c36dT7pAf9TkGQjj88jxw624xHaL6wtXJTWCt"
}

###
# @name Cancel Trust Request
POST: /cancel_trust_request
Host: {{hostname}}:{{port}}

{
    "mnemonic": "captain calm afraid vehicle fetch stage custom federal assist arrange pumpkin cheese grocery square discover firm kind endorse door tonight name lonely alter wrestle",
    "address": "5CwBjJ48HW7c36dT7pAf9TkGQjj88jxw624xHaL6wtXJTWCt"
}

###
# @name Check Trust Exists
POST: /check_trust_exists
Host: {{hostname}}:{{port}}

{
    "address1": "5CwBjJ48HW7c36dT7pAf9TkGQjj88jxw624xHaL6wtXJTWCt",
    "address2": "5CwBjJ48HW7c36dT7pAf9TkGQjj88jxw624xHaL6wtXJTWCt"
}

###
# @name Get Trust History
POST: /get_trust_history
Host: {{hostname}}:{{port}}